import json
import sys
from threading import Lock
import numpy as np
import tensorflow as tf
from app.config import settings
from app.utils.logger import logger

# The trained artifact contains Lambda functions defined in training/model.py.
# Import that module so the Lambda globals (notably TensorFlow) are available
# when Keras executes the saved functions during inference.
TRAINING_DIR = settings.resolve("training")
if str(TRAINING_DIR) not in sys.path:
    sys.path.insert(0, str(TRAINING_DIR))
try:
    import model as _training_model  # noqa: F401
except ImportError:
    _training_model = None

class ModelService:
    def __init__(self):
        self.model = None
        self.encoder_body = None
        self.config = None
        self._lock = Lock()

    def load(self):
        with self._lock:
            if self.model is not None: return
            model_path, config_path = settings.resolve(settings.model_path), settings.resolve(settings.model_config_path)
            logger.info("Loading Siamese model...")
            if not model_path.exists(): raise FileNotFoundError(f"Model not found: {model_path}")
            if not config_path.exists(): raise FileNotFoundError(f"Model config not found: {config_path}")
            # This artifact is generated by our own training code and contains
            # Lambda layers used to compute the embedding distance.
            self.model = tf.keras.models.load_model(model_path, compile=False, safe_mode=False)
            # Avoid executing serialized Lambda callables during inference.
            # The encoder output immediately before its normalization Lambda is
            # stable, so normalize it explicitly below.
            encoder = self.model.get_layer("signature_encoder")
            embedding = encoder.get_layer("embedding")
            self.encoder_body = tf.keras.Model(encoder.input, embedding.input)
            self.config = json.loads(config_path.read_text(encoding="utf-8"))
            logger.info("Model loaded successfully. Threshold loaded: %s", self.threshold)

    @property
    def loaded(self): return self.model is not None
    @property
    def threshold(self): return float(settings.model_threshold if settings.model_threshold is not None else self.config["threshold"])
    def predict_distance(self, image_a, image_b):
        if not self.loaded: raise RuntimeError("Model is not loaded")
        embeddings = self.encoder_body.predict(np.concatenate([image_a, image_b], axis=0), verbose=0)
        embeddings = tf.math.l2_normalize(embeddings, axis=1).numpy()
        return float(np.sqrt(np.sum(np.square(embeddings[0] - embeddings[1])) + np.finfo(np.float32).eps))

model_service = ModelService()
